### ISSUE TITLE
Using multiple appender causes ConcurrentModificationException

### ISSUE THREAD

**Issue by plinioasf** [soleaf/ErRabbit#19]
I'm using https://github.com/plinioasf/ErRabbit-logback-log4j-appender that enables logs from log4j and logback to go to ErRabbit. I'm seeing the following error sometimes:

2016-07-22 16:39:20.325 ERROR 2038 --- [eBrokerSockJS-6] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at org.mintcode.errabbit.core.collect.LogMessageListener.flushCache(LogMessageListener.java:138)
    at org.mintcode.errabbit.core.collect.LogMessageListener.checkCache(LogMessageListener.java:119)
    at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by oy-ilho** [comment]
Sorry. It's just fixed now. and released
Thank you.
